name = "immeit"
main = "worker.js"
compatibility_date = "2025-04-01"
workers_dev = true

[vars]
SG_B64 = "VTBjdWFWTXdjV2hJU210VVZuVnhhR2xqUjBoU1pFbERVUzVqZHpoeVFrSkhXRFpuTkVkRFJsZGtlbEJPWW10WWRqa3pja04wU1hKZlZXd3pkMUV5YkdKemQwMUY="

[env.production]
workers_dev = true
